"""add_two_factor_secret_column

Revision ID: 860bc0e14915
Revises: 052d31179dc3
Create Date: 2026-01-16 10:56:54.471355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860bc0e14915'
down_revision: Union[str, Sequence[str], None] = '052d31179dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_settings', sa.Column('two_factor_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_settings', 'two_factor_secret')
    # ### end Alembic commands ###
