"""Added relationships

Revision ID: d3e1ea8e5d6b
Revises: afac11e6a871
Create Date: 2025-11-16 17:20:20.165151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e1ea8e5d6b'
down_revision: Union[str, Sequence[str], None] = 'afac11e6a871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_transactions', sa.Column('payout_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ledger_transactions_payout_id'), 'ledger_transactions', ['payout_id'], unique=False)
    op.create_foreign_key(None, 'ledger_transactions', 'payouts', ['payout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledger_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_ledger_transactions_payout_id'), table_name='ledger_transactions')
    op.drop_column('ledger_transactions', 'payout_id')
    # ### end Alembic commands ###
